<a href="https://colab.research.google.com/github/Praxis-QR/DeepLearning/blob/main/AI_DL_Chapter_2_Neural_Networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![alt text](https://1.bp.blogspot.com/-WAjYIaQofo0/YEB0cQsSGSI/AAAAAAAAkoE/TpQcWBRGtu0N010lmiTS9cFHuGwXB45PQCLcBGAsYHQ/s16000/colabHeader00.png)<br>

<hr>

[Prithwis Mukerjee](http://www.yantrajaal.com) / [Praxis Business School](http://praxis.ac.in/) / [Book Website](http://aidl4managers.blogspot.com) 

Base Solultion https://stackoverflow.com/questions/37520849/cant-approximate-simple-multiplication-function-in-neural-network-with-1-hidden <br>
Overview of NN https://machinelearningmastery.com/tutorial-first-neural-network-python-keras/

In [1]:
import numpy as np
from keras import layers
from keras import models
from keras import callbacks

In [2]:
test=[[.2,.5],[.3,.6],[.4,.7],[.5,.8],[.6,.9]]

In [3]:
train = np.random.random((10000, 2))
results = np.asarray([a * b for a, b in train])
train[0:5,:], results[0:5]

(array([[0.3880332 , 0.55489982],
        [0.8559714 , 0.46600363],
        [0.46314092, 0.02380023],
        [0.14684517, 0.05011848],
        [0.08990294, 0.31105579]]),
 array([0.21531955, 0.39888578, 0.01102286, 0.00735966, 0.02796483]))

#Simple Model modelS

In [4]:
model1 = models.Sequential()
model1.add(layers.Dense(150, activation='relu', input_shape=(2,)))
model1.add(layers.Dense(1, activation='relu'))
model1.compile(optimizer='sgd', loss='mae')
model1.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 150)               450       
                                                                 
 dense_1 (Dense)             (None, 1)                 151       
                                                                 
Total params: 601
Trainable params: 601
Non-trainable params: 0
_________________________________________________________________


In [5]:
model1.fit(train, results, epochs=5, batch_size=1)
#model1.fit(train, results, epochs=5)               # if no batch size is specified, size 32 is taken, hence 313 batches, 1 sample from each batch

Epoch 1/5
10000/10000 [==============================] - 14s 1ms/step - loss: 0.0316
Epoch 2/5
10000/10000 [==============================] - 13s 1ms/step - loss: 0.0175
Epoch 3/5
10000/10000 [==============================] - 12s 1ms/step - loss: 0.0118
Epoch 4/5
10000/10000 [==============================] - 13s 1ms/step - loss: 0.0113
Epoch 5/5
10000/10000 [==============================] - 13s 1ms/step - loss: 0.0110


In [6]:
test_result = model1.predict(test)
test,test_result

1/1 [==============================] - 0s 168ms/step


([[0.2, 0.5], [0.3, 0.6], [0.4, 0.7], [0.5, 0.8], [0.6, 0.9]],
 array([[0.09581982],
        [0.1808732 ],
        [0.28368556],
        [0.41351584],
        [0.54719645]], dtype=float32))

In [ ]:
junk_answers = np.random.random((10000, 1))
model1.fit(train, junk_answers, epochs=5, batch_size=1)
test_result = model1.predict(test)
test,test_result

Epoch 1/5
10000/10000 [==============================] - 18s 2ms/step - loss: 0.5006
Epoch 2/5
10000/10000 [==============================] - 17s 2ms/step - loss: 0.5006
Epoch 3/5
10000/10000 [==============================] - 16s 2ms/step - loss: 0.5006
Epoch 4/5
10000/10000 [==============================] - 16s 2ms/step - loss: 0.5006
Epoch 5/5
1/1 [==============================] - 0s 31ms/step


([[0.2, 0.5], [0.3, 0.6], [0.4, 0.7], [0.5, 0.8], [0.6, 0.9]], array([[0.],
        [0.],
        [0.],
        [0.],
        [0.]], dtype=float32))

In [7]:
##Last Tested
!date

Wed 01 Feb 2023 08:38:24 AM UTC


#Chronobooks <br>
![alt text](https://1.bp.blogspot.com/-lTiYBkU2qbU/X1er__fvnkI/AAAAAAAAjtE/GhDR3OEGJr4NG43fZPodrQD5kbxtnKebgCLcBGAsYHQ/s600/Footer2020-600x200.png)<hr>
Chronotantra and Chronoyantra are two science fiction novels that explore the collapse of human civilisation on Earth and then its rebirth and reincarnation both on Earth as well as on the distant worlds of Mars, Titan and Enceladus. But is it the human civilisation that is being reborn? Or is it some other sentience that is revealing itself. 
If you have an interest in AI and found this material useful, you may consider buying these novels, in paperback or kindle, from [http://bit.ly/chronobooks](http://bit.ly/chronobooks)

![CC-BY-SA](https://licensebuttons.net/l/by-sa/3.0/88x31.png) The contents of this website are released under creative commons 