<a href="https://colab.research.google.com/github/Praxis-QR/DeepLearning/blob/main/AI_DL_Chapter_2_Neural_Networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![alt text](https://1.bp.blogspot.com/-WAjYIaQofo0/YEB0cQsSGSI/AAAAAAAAkoE/TpQcWBRGtu0N010lmiTS9cFHuGwXB45PQCLcBGAsYHQ/s16000/colabHeader00.png)<br>

<hr>

[Prithwis Mukerjee](http://www.yantrajaal.com) / [Praxis Business School](http://praxis.ac.in/) / [Book Website](http://aidl4managers.blogspot.com) 

Base Solultion https://stackoverflow.com/questions/37520849/cant-approximate-simple-multiplication-function-in-neural-network-with-1-hidden <br>
Overview of NN https://machinelearningmastery.com/tutorial-first-neural-network-python-keras/

In [1]:
import numpy as np
from keras import layers
from keras import models
from keras import callbacks

In [2]:
test=[[.2,.5],[.3,.6],[.4,.7],[.5,.8],[.6,.9]]

In [3]:
train = np.random.random((10000, 2))
results = np.asarray([a * b for a, b in train])
train[0:5,:], results[0:5]

(array([[0.44724225, 0.87311121],
        [0.4948484 , 0.66900011],
        [0.92020358, 0.13239155],
        [0.66053506, 0.03575621],
        [0.6053147 , 0.52097956]]),
 array([0.39049222, 0.33105364, 0.12182718, 0.02361823, 0.31535659]))

#Simple Model modelS

In [4]:
model1 = models.Sequential()
model1.add(layers.Dense(150, activation='relu', input_shape=(2,)))
model1.add(layers.Dense(1, activation='relu'))
model1.compile(optimizer='sgd', loss='mae')
model1.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 150)               450       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 151       
Total params: 601
Trainable params: 601
Non-trainable params: 0
_________________________________________________________________


In [5]:
model1.fit(train, results, epochs=5, batch_size=1)
#model1.fit(train, results, epochs=5)               # if no batch size is specified, size 32 is taken, hence 313 batches, 1 sample from each batch

Epoch 1/5
10000/10000 [==============================] - 10s 966us/step - loss: 0.0314
Epoch 2/5
10000/10000 [==============================] - 10s 980us/step - loss: 0.0186
Epoch 3/5
10000/10000 [==============================] - 10s 973us/step - loss: 0.0118
Epoch 4/5
10000/10000 [==============================] - 10s 979us/step - loss: 0.0112
Epoch 5/5
10000/10000 [==============================] - 10s 962us/step - loss: 0.0108


In [6]:
test_result = model1.predict(test)
test,test_result

([[0.2, 0.5], [0.3, 0.6], [0.4, 0.7], [0.5, 0.8], [0.6, 0.9]],
 array([[0.09526977],
        [0.17112945],
        [0.26456475],
        [0.38195527],
        [0.5235787 ]], dtype=float32))

In [7]:
junk_answers = np.random.random((10000, 1))
model1.fit(train, junk_answers, epochs=5, batch_size=1)
test_result = model1.predict(test)
test,test_result

Epoch 1/5
10000/10000 [==============================] - 14s 1ms/step - loss: 0.2550
Epoch 2/5
10000/10000 [==============================] - 14s 1ms/step - loss: 0.2529
Epoch 3/5
10000/10000 [==============================] - 14s 1ms/step - loss: 0.2532
Epoch 4/5
10000/10000 [==============================] - 14s 1ms/step - loss: 0.2533
Epoch 5/5
10000/10000 [==============================] - 14s 1ms/step - loss: 0.2528


([[0.2, 0.5], [0.3, 0.6], [0.4, 0.7], [0.5, 0.8], [0.6, 0.9]],
 array([[0.49484527],
        [0.4967107 ],
        [0.49961913],
        [0.50288874],
        [0.50615853]], dtype=float32))

#Chronobooks <br>
![alt text](https://1.bp.blogspot.com/-lTiYBkU2qbU/X1er__fvnkI/AAAAAAAAjtE/GhDR3OEGJr4NG43fZPodrQD5kbxtnKebgCLcBGAsYHQ/s600/Footer2020-600x200.png)<hr>
Chronotantra and Chronoyantra are two science fiction novels that explore the collapse of human civilisation on Earth and then its rebirth and reincarnation both on Earth as well as on the distant worlds of Mars, Titan and Enceladus. But is it the human civilisation that is being reborn? Or is it some other sentience that is revealing itself. 
If you have an interest in AI and found this material useful, you may consider buying these novels, in paperback or kindle, from [http://bit.ly/chronobooks](http://bit.ly/chronobooks)

![CC-BY-SA](https://licensebuttons.net/l/by-sa/3.0/88x31.png) The contents of this website are released under creative commons 