<a href="https://colab.research.google.com/github/Praxis-QR/DeepLearning/blob/main/AI_DL_Chapter_3_Under_the_Hood.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![alt text](https://1.bp.blogspot.com/-WAjYIaQofo0/YEB0cQsSGSI/AAAAAAAAkoE/TpQcWBRGtu0N010lmiTS9cFHuGwXB45PQCLcBGAsYHQ/s16000/colabHeader00.png)<br>

<hr>

[Prithwis Mukerjee](http://www.yantrajaal.com) / [Praxis Business School](http://praxis.ac.in/) / [Book Website](http://aidl4managers.blogspot.com) 

Base Solultion https://stackoverflow.com/questions/37520849/cant-approximate-simple-multiplication-function-in-neural-network-with-1-hidden <br>
Overview of NN https://machinelearningmastery.com/tutorial-first-neural-network-python-keras/

In [1]:
import numpy as np


In [2]:
test=[[.2,.5],[.3,.6],[.4,.7],[.5,.8],[.6,.9]]

In [3]:
train = np.random.random((10000, 2))
results = np.asarray([a * b for a, b in train])
train[0:5,:], results[0:5]

(array([[0.41486323, 0.7470981 ],
        [0.82140391, 0.63749929],
        [0.63782051, 0.90215892],
        [0.54898375, 0.14132535],
        [0.65262974, 0.28962669]]),
 array([0.30994353, 0.52364441, 0.57541547, 0.07758532, 0.18901899]))

#Simple Model model1

In [4]:
from keras import layers
from keras import models
from keras import callbacks

In [8]:
model1B = models.Sequential()
model1B.add(layers.Dense(150, activation='relu', input_shape=(2,)))
model1B.add(layers.Dense(1, activation='relu'))
model1B.compile(optimizer='sgd', loss='mae')
model1B.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 150)               450       
                                                                 
 dense_3 (Dense)             (None, 1)                 151       
                                                                 
Total params: 601
Trainable params: 601
Non-trainable params: 0
_________________________________________________________________


In [9]:
model1B.fit(train, results, epochs=5, batch_size=1)
#model1.fit(train, results, epochs=5)

Epoch 1/5
10000/10000 [==============================] - 12s 1ms/step - loss: 0.0288
Epoch 2/5
10000/10000 [==============================] - 12s 1ms/step - loss: 0.0136
Epoch 3/5
10000/10000 [==============================] - 13s 1ms/step - loss: 0.0118
Epoch 4/5
10000/10000 [==============================] - 12s 1ms/step - loss: 0.0112
Epoch 5/5
10000/10000 [==============================] - 12s 1ms/step - loss: 0.0109


In [10]:
test_result = model1B.predict(test)
test,test_result

([[0.2, 0.5], [0.3, 0.6], [0.4, 0.7], [0.5, 0.8], [0.6, 0.9]],
 array([[0.11603371],
        [0.19596484],
        [0.2988634 ],
        [0.41728818],
        [0.5564184 ]], dtype=float32))

#Better Model : model2

In [11]:
model2A = models.Sequential()
model2A.add(layers.Dense(4096*4, activation='relu', input_shape=(2,)))
model2A.add(layers.Dense(1, activation='linear'))
model2A.compile(optimizer='adam', loss='mse')
model2A.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 16384)             49152     
                                                                 
 dense_5 (Dense)             (None, 1)                 16385     
                                                                 
Total params: 65,537
Trainable params: 65,537
Non-trainable params: 0
_________________________________________________________________


In [12]:
model2A.fit(train, results, epochs=100, batch_size=512)

Epoch 1/100
20/20 [==============================] - 1s 55ms/step - loss: 0.0264
Epoch 2/100
20/20 [==============================] - 1s 55ms/step - loss: 0.0029
Epoch 3/100
20/20 [==============================] - 1s 54ms/step - loss: 0.0015
Epoch 4/100
20/20 [==============================] - 1s 53ms/step - loss: 0.0011
Epoch 5/100
20/20 [==============================] - 1s 53ms/step - loss: 7.7361e-04
Epoch 6/100
20/20 [==============================] - 1s 53ms/step - loss: 5.2653e-04
Epoch 7/100
20/20 [==============================] - 1s 54ms/step - loss: 3.3572e-04
Epoch 8/100
20/20 [==============================] - 1s 53ms/step - loss: 2.0407e-04
Epoch 9/100
20/20 [==============================] - 1s 54ms/step - loss: 1.2945e-04
Epoch 10/100
20/20 [==============================] - 1s 55ms/step - loss: 9.1137e-05
Epoch 11/100
20/20 [==============================] - 1s 55ms/step - loss: 6.8813e-05
Epoch 12/100
20/20 [==============================] - 1s 53ms/step - loss: 5.31

In [13]:
test_results_2A = model2A.predict(test)
test,test_results_2A

([[0.2, 0.5], [0.3, 0.6], [0.4, 0.7], [0.5, 0.8], [0.6, 0.9]],
 array([[0.1002232 ],
        [0.18029156],
        [0.28022423],
        [0.40044835],
        [0.5404367 ]], dtype=float32))

In [14]:
test_result = model1B.predict(test)
test,test_result

([[0.2, 0.5], [0.3, 0.6], [0.4, 0.7], [0.5, 0.8], [0.6, 0.9]],
 array([[0.11603371],
        [0.19596484],
        [0.2988634 ],
        [0.41728818],
        [0.5564184 ]], dtype=float32))

In [15]:
from keras import callbacks
callbacks = [callbacks.EarlyStopping(patience=6), callbacks.ReduceLROnPlateau()]
model2A.fit(train, results, epochs=100, batch_size=512, validation_split=0.3, callbacks=callbacks)

Epoch 1/100
14/14 [==============================] - 1s 74ms/step - loss: 2.0250e-07 - val_loss: 3.9083e-07 - lr: 0.0010
Epoch 2/100
14/14 [==============================] - 1s 62ms/step - loss: 2.3732e-07 - val_loss: 1.9747e-07 - lr: 0.0010
Epoch 3/100
14/14 [==============================] - 1s 64ms/step - loss: 1.7460e-07 - val_loss: 1.6095e-07 - lr: 0.0010
Epoch 4/100
14/14 [==============================] - 1s 64ms/step - loss: 1.5382e-07 - val_loss: 1.3321e-07 - lr: 0.0010
Epoch 5/100
14/14 [==============================] - 1s 64ms/step - loss: 1.6397e-07 - val_loss: 1.2850e-07 - lr: 0.0010
Epoch 6/100
14/14 [==============================] - 1s 63ms/step - loss: 1.5955e-07 - val_loss: 1.3408e-07 - lr: 0.0010
Epoch 7/100
14/14 [==============================] - 1s 64ms/step - loss: 1.8450e-07 - val_loss: 3.3214e-07 - lr: 0.0010
Epoch 8/100
14/14 [==============================] - 1s 63ms/step - loss: 1.8721e-07 - val_loss: 2.4359e-07 - lr: 0.0010
Epoch 9/100
14/14 [=============

In [17]:
test_results_2 = model2A.predict(test)
test,test_results_2

([[0.2, 0.5], [0.3, 0.6], [0.4, 0.7], [0.5, 0.8], [0.6, 0.9]],
 array([[0.09987218],
        [0.17976484],
        [0.27954772],
        [0.39958486],
        [0.5393298 ]], dtype=float32))

#Bad Data

In [18]:
from keras import callbacks

junk = np.random.random((10000, 1))
model2C = models.Sequential()
model2C.add(layers.Dense(4096*4, activation='relu', input_shape=(2,)))
model2C.add(layers.Dense(1, activation='linear'))
model2C.compile(optimizer='adam', loss='mse')

callbacks = [callbacks.EarlyStopping(patience=6), callbacks.ReduceLROnPlateau()]
model2C.fit(train, junk, epochs=100, batch_size=512, validation_split=0.3, callbacks=callbacks)

Epoch 1/100
14/14 [==============================] - 1s 70ms/step - loss: 0.1394 - val_loss: 0.1172 - lr: 0.0010
Epoch 2/100
14/14 [==============================] - 1s 66ms/step - loss: 0.0966 - val_loss: 0.0913 - lr: 0.0010
Epoch 3/100
14/14 [==============================] - 1s 63ms/step - loss: 0.0866 - val_loss: 0.0867 - lr: 0.0010
Epoch 4/100
14/14 [==============================] - 1s 63ms/step - loss: 0.0845 - val_loss: 0.0864 - lr: 0.0010
Epoch 5/100
14/14 [==============================] - 1s 63ms/step - loss: 0.0841 - val_loss: 0.0862 - lr: 0.0010
Epoch 6/100
14/14 [==============================] - 1s 62ms/step - loss: 0.0840 - val_loss: 0.0865 - lr: 0.0010
Epoch 7/100
14/14 [==============================] - 1s 62ms/step - loss: 0.0845 - val_loss: 0.0862 - lr: 0.0010
Epoch 8/100
14/14 [==============================] - 1s 62ms/step - loss: 0.0841 - val_loss: 0.0864 - lr: 0.0010
Epoch 9/100
14/14 [==============================] - 1s 63ms/step - loss: 0.0842 - val_loss: 0.0

In [19]:
test_results_2C = model2C.predict(test)
test,test_results_2C

([[0.2, 0.5], [0.3, 0.6], [0.4, 0.7], [0.5, 0.8], [0.6, 0.9]],
 array([[0.52025425],
        [0.5201312 ],
        [0.5166615 ],
        [0.51767635],
        [0.5211427 ]], dtype=float32))

In [20]:
#Save and Load Models
model2A.save('savedModel')


In [21]:
from tensorflow import keras
model3 = keras.models.load_model('savedModel')


In [22]:
test_result3 = model3.predict(test)
test,test_result3

([[0.2, 0.5], [0.3, 0.6], [0.4, 0.7], [0.5, 0.8], [0.6, 0.9]],
 array([[0.09987218],
        [0.17976484],
        [0.27954772],
        [0.39958486],
        [0.5393298 ]], dtype=float32))

In [24]:
## Last Tested
!date

Sun Aug 28 09:38:45 UTC 2022


#Chronobooks <br>
![alt text](https://1.bp.blogspot.com/-lTiYBkU2qbU/X1er__fvnkI/AAAAAAAAjtE/GhDR3OEGJr4NG43fZPodrQD5kbxtnKebgCLcBGAsYHQ/s600/Footer2020-600x200.png)<hr>
Chronotantra and Chronoyantra are two science fiction novels that explore the collapse of human civilisation on Earth and then its rebirth and reincarnation both on Earth as well as on the distant worlds of Mars, Titan and Enceladus. But is it the human civilisation that is being reborn? Or is it some other sentience that is revealing itself. 
If you have an interest in AI and found this material useful, you may consider buying these novels, in paperback or kindle, from [http://bit.ly/chronobooks](http://bit.ly/chronobooks)

![CC-BY-SA](https://licensebuttons.net/l/by-sa/3.0/88x31.png) The contents of this website are released under creative commons 