<a href="https://colab.research.google.com/github/Praxis-QR/DeepLearning/blob/main/AI_DL_Chapter_3_Under_the_Hood.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![alt text](https://1.bp.blogspot.com/-WAjYIaQofo0/YEB0cQsSGSI/AAAAAAAAkoE/TpQcWBRGtu0N010lmiTS9cFHuGwXB45PQCLcBGAsYHQ/s16000/colabHeader00.png)<br>

<hr>

[Prithwis Mukerjee](http://www.yantrajaal.com) / [Praxis Business School](http://praxis.ac.in/) / [Book Website](http://aidl4managers.blogspot.com) 

Base Solultion https://stackoverflow.com/questions/37520849/cant-approximate-simple-multiplication-function-in-neural-network-with-1-hidden <br>
Overview of NN https://machinelearningmastery.com/tutorial-first-neural-network-python-keras/

In [1]:
import numpy as np


In [2]:
test=[[.2,.5],[.3,.6],[.4,.7],[.5,.8],[.6,.9]]

In [3]:
train = np.random.random((10000, 2))
results = np.asarray([a * b for a, b in train])
train[0:5,:], results[0:5]

(array([[0.33121262, 0.67529016],
        [0.67481703, 0.49547644],
        [0.88356318, 0.58703341],
        [0.27489573, 0.52240322],
        [0.91571077, 0.6208719 ]]),
 array([0.22366462, 0.33435594, 0.51868111, 0.14360641, 0.56853909]))

#Simple Model model1

In [4]:
from keras import layers
from keras import models
from keras import callbacks

In [5]:
model1 = models.Sequential()
model1.add(layers.Dense(150, activation='relu', input_shape=(2,)))
model1.add(layers.Dense(1, activation='relu'))
model1.compile(optimizer='sgd', loss='mae')
model1.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 150)               450       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 151       
Total params: 601
Trainable params: 601
Non-trainable params: 0
_________________________________________________________________


In [6]:
model1.fit(train, results, epochs=5, batch_size=1)
#model1.fit(train, results, epochs=5)

Epoch 1/5
10000/10000 [==============================] - 9s 902us/step - loss: 0.0279
Epoch 2/5
10000/10000 [==============================] - 9s 902us/step - loss: 0.0130
Epoch 3/5
10000/10000 [==============================] - 9s 908us/step - loss: 0.0118
Epoch 4/5
10000/10000 [==============================] - 9s 923us/step - loss: 0.0113
Epoch 5/5
10000/10000 [==============================] - 9s 923us/step - loss: 0.0110


In [7]:
test_result = model1.predict(test)
test,test_result

([[0.2, 0.5], [0.3, 0.6], [0.4, 0.7], [0.5, 0.8], [0.6, 0.9]],
 array([[0.09191382],
        [0.16642466],
        [0.2581013 ],
        [0.3729803 ],
        [0.51872003]], dtype=float32))

#Better Model : model2

In [8]:
model2 = models.Sequential()
model2.add(layers.Dense(4096*4, activation='relu', input_shape=(2,)))
model2.add(layers.Dense(1, activation='linear'))
model2.compile(optimizer='adam', loss='mse')
model2.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 16384)             49152     
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 16385     
Total params: 65,537
Trainable params: 65,537
Non-trainable params: 0
_________________________________________________________________


In [9]:
model2.fit(train, results, epochs=100, batch_size=512)

Epoch 1/100
20/20 [==============================] - 1s 54ms/step - loss: 0.0268
Epoch 2/100
20/20 [==============================] - 1s 52ms/step - loss: 0.0030
Epoch 3/100
20/20 [==============================] - 1s 52ms/step - loss: 0.0016
Epoch 4/100
20/20 [==============================] - 1s 52ms/step - loss: 0.0011
Epoch 5/100
20/20 [==============================] - 1s 52ms/step - loss: 7.5649e-04
Epoch 6/100
20/20 [==============================] - 1s 51ms/step - loss: 4.8039e-04
Epoch 7/100
20/20 [==============================] - 1s 50ms/step - loss: 2.9679e-04
Epoch 8/100
20/20 [==============================] - 1s 52ms/step - loss: 1.7906e-04
Epoch 9/100
20/20 [==============================] - 1s 50ms/step - loss: 1.1599e-04
Epoch 10/100
20/20 [==============================] - 1s 54ms/step - loss: 8.3020e-05
Epoch 11/100
20/20 [==============================] - 1s 52ms/step - loss: 6.3492e-05
Epoch 12/100
20/20 [==============================] - 1s 51ms/step - loss: 5.14

In [10]:
test_results_2 = model2.predict(test)
test,test_results_2

([[0.2, 0.5], [0.3, 0.6], [0.4, 0.7], [0.5, 0.8], [0.6, 0.9]],
 array([[0.10022731],
        [0.18026012],
        [0.28031385],
        [0.40050676],
        [0.540549  ]], dtype=float32))

In [11]:
test_result = model1.predict(test)
test,test_result

([[0.2, 0.5], [0.3, 0.6], [0.4, 0.7], [0.5, 0.8], [0.6, 0.9]],
 array([[0.09191382],
        [0.16642466],
        [0.2581013 ],
        [0.3729803 ],
        [0.51872003]], dtype=float32))

In [12]:
from keras import callbacks
callbacks = [callbacks.EarlyStopping(patience=6), callbacks.ReduceLROnPlateau()]
model2.fit(train, results, epochs=100, batch_size=512, validation_split=0.3, callbacks=callbacks)

Epoch 1/100
14/14 [==============================] - 1s 69ms/step - loss: 2.1733e-07 - val_loss: 1.3033e-07
Epoch 2/100
14/14 [==============================] - 1s 60ms/step - loss: 1.6781e-07 - val_loss: 1.5371e-07
Epoch 3/100
14/14 [==============================] - 1s 60ms/step - loss: 1.4862e-07 - val_loss: 1.2654e-07
Epoch 4/100
14/14 [==============================] - 1s 59ms/step - loss: 1.3931e-07 - val_loss: 1.3574e-07
Epoch 5/100
14/14 [==============================] - 1s 61ms/step - loss: 1.8291e-07 - val_loss: 1.7489e-07
Epoch 6/100
14/14 [==============================] - 1s 60ms/step - loss: 1.9401e-07 - val_loss: 1.6752e-07
Epoch 7/100
14/14 [==============================] - 1s 59ms/step - loss: 1.6330e-07 - val_loss: 1.6966e-07
Epoch 8/100
14/14 [==============================] - 1s 61ms/step - loss: 2.1480e-07 - val_loss: 1.9269e-07
Epoch 9/100
14/14 [==============================] - 1s 60ms/step - loss: 1.7857e-07 - val_loss: 1.1429e-07
Epoch 10/100
14/14 [========

In [13]:
test_results_2 = model2.predict(test)
test,test_results_2

([[0.2, 0.5], [0.3, 0.6], [0.4, 0.7], [0.5, 0.8], [0.6, 0.9]],
 array([[0.10001156],
        [0.17998289],
        [0.27995598],
        [0.40002903],
        [0.5399832 ]], dtype=float32))

#Bad Data

In [14]:
from keras import callbacks

junk = np.random.random((10000, 1))
model2 = models.Sequential()
model2.add(layers.Dense(4096*4, activation='relu', input_shape=(2,)))
model2.add(layers.Dense(1, activation='linear'))
model2.compile(optimizer='adam', loss='mse')

callbacks = [callbacks.EarlyStopping(patience=6), callbacks.ReduceLROnPlateau()]
model2.fit(train, junk, epochs=100, batch_size=512, validation_split=0.3, callbacks=callbacks)

Epoch 1/100
14/14 [==============================] - 1s 66ms/step - loss: 0.1412 - val_loss: 0.1119
Epoch 2/100
14/14 [==============================] - 1s 60ms/step - loss: 0.0992 - val_loss: 0.0867
Epoch 3/100
14/14 [==============================] - 1s 62ms/step - loss: 0.0879 - val_loss: 0.0827
Epoch 4/100
14/14 [==============================] - 1s 61ms/step - loss: 0.0861 - val_loss: 0.0825
Epoch 5/100
14/14 [==============================] - 1s 60ms/step - loss: 0.0854 - val_loss: 0.0825
Epoch 6/100
14/14 [==============================] - 1s 60ms/step - loss: 0.0853 - val_loss: 0.0824
Epoch 7/100
14/14 [==============================] - 1s 60ms/step - loss: 0.0853 - val_loss: 0.0822
Epoch 8/100
14/14 [==============================] - 1s 60ms/step - loss: 0.0853 - val_loss: 0.0823
Epoch 9/100
14/14 [==============================] - 1s 60ms/step - loss: 0.0853 - val_loss: 0.0828
Epoch 10/100
14/14 [==============================] - 1s 60ms/step - loss: 0.0851 - val_loss: 0.0823

In [15]:
test_results_2 = model2.predict(test)
test,test_results_2

([[0.2, 0.5], [0.3, 0.6], [0.4, 0.7], [0.5, 0.8], [0.6, 0.9]],
 array([[0.5131522 ],
        [0.51174074],
        [0.5107579 ],
        [0.5099194 ],
        [0.5098976 ]], dtype=float32))

In [16]:
#Save and Load Models
model1.save('savedModel')


INFO:tensorflow:Assets written to: savedModel/assets


In [17]:
from tensorflow import keras
model3 = keras.models.load_model('savedModel')


In [18]:
test_result3 = model3.predict(test)
test,test_result3

([[0.2, 0.5], [0.3, 0.6], [0.4, 0.7], [0.5, 0.8], [0.6, 0.9]],
 array([[0.09191382],
        [0.16642466],
        [0.2581013 ],
        [0.3729803 ],
        [0.51872003]], dtype=float32))

#Chronobooks <br>
![alt text](https://1.bp.blogspot.com/-lTiYBkU2qbU/X1er__fvnkI/AAAAAAAAjtE/GhDR3OEGJr4NG43fZPodrQD5kbxtnKebgCLcBGAsYHQ/s600/Footer2020-600x200.png)<hr>
Chronotantra and Chronoyantra are two science fiction novels that explore the collapse of human civilisation on Earth and then its rebirth and reincarnation both on Earth as well as on the distant worlds of Mars, Titan and Enceladus. But is it the human civilisation that is being reborn? Or is it some other sentience that is revealing itself. 
If you have an interest in AI and found this material useful, you may consider buying these novels, in paperback or kindle, from [http://bit.ly/chronobooks](http://bit.ly/chronobooks)

![CC-BY-SA](https://licensebuttons.net/l/by-sa/3.0/88x31.png) The contents of this website are released under creative commons 